server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/qa_users
    username: test1
    password: test1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration,classpath:qa/migration
